### ISSUE TITLE
多个商品监控通知逻辑

### ISSUE THREAD

**Issue by ghxx2016** [zhuweitung/jd-stock#2]
多个商品监控若一个商品无货，就无法触发通知

**Comment by ghxx2016** [comment]
另外请问多商品配置文件的写法是怎样？另起一行还是用分隔符？

**Comment by zhuweitung** [comment]
```yaml
skuInfos: # 监控商品信息
  - id: 100014150579
    name: 蓝漂XPLUS会员联名款 抽纸4层100抽*20包
  - id: 100071501514
    name: 小米路由器BE6500Pro

```
